### ISSUE TITLE
What a shame!

### ISSUE THREAD

**Issue by 3D-I** [phpbb-seo/Mobbern#1]
LOL, what a leecher. 💩

You should learn to write at least one line of code in any language before taking over someone else's work inpunctually, we all know you are not a programmer. It's shameful what you do, moreover you ask for help to users of various forums both privately and publicly (also for a fee) because you have never been able to do anything, even as a translator you are not worth much. 

Shame on you.

**Comment by meis2m** [comment]
> 

stfu

**Comment by 3D-I** [comment]
This is you. Poor guy. Stay tuned for the next.

![image](https://user-images.githubusercontent.com/480857/152106879-2cb0eb90-0d6f-42bf-bad5-4419d3b96da1.png)

**Comment by 3D-I** [comment]
This proves your absolute noobness, one of many.

![image](https://user-images.githubusercontent.com/480857/152107495-a1b486e7-780a-420f-a268-c4b8b528b256.png)

**Comment by 3D-I** [comment]
Shall I go ahead?

**Comment by 3D-I** [comment]
Yet another one! You said YOU WROTE IT but it was written by VIETBB!
And you are asking for paid help!

![image](https://user-images.githubusercontent.com/480857/152109319-5ca19d06-584b-4da5-9e67-0f210ea8ca65.png)
